id: IE1711757
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T16:55:23+00:00'
last_modified: '2022-06-08T05:53:05.293661+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ1163
  title: གཤིན་རྗེ་གཤེད་ཀྱི་རྫོགས་རིམ་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    FC27:
      image_group_id: I1CZ1590
      title: ''
      total_pages: 22
      order: 1
      base_file: FC27.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
